/* ============================================================
 * monsters.js — 怪物清单（由 tools/scan-monsters.js 自动生成）
 * 显示顺序与分组见 data/monster-order.json；改名/增删后请重跑
 *   node tools/scan-monsters.js
 * ============================================================ */
window.MHRS_MONSTERS = [
  { id: 'm04', file: '镰鼬龙王.png', tier: 'EX1', name: '镰鼬龙王' },
  { id: 'm02', file: '眠狗龙王.png', tier: 'EX1', name: '眠狗龙王' },
  { id: 'm03', file: '毒狗龙王.png', tier: 'EX1', name: '毒狗龙王' },
  { id: 'm01', file: '搔鸟.png', tier: 'EX1', name: '搔鸟' },
  { id: 'm05', file: '赤甲兽.png', tier: 'EX1', name: '赤甲兽' },
  { id: 'm06', file: '白兔兽.png', tier: 'EX1', name: '白兔兽' },
  { id: 'm07', file: '青熊兽.png', tier: 'EX1', name: '青熊兽' },
  { id: 'm08', file: '大名盾蟹.png', tier: 'EX2', name: '大名盾蟹' },
  { id: 'm09', file: '天狗兽.png', tier: 'EX2', name: '天狗兽' },
  { id: 'm10', file: '奇怪龙.png', tier: 'EX2', name: '奇怪龙' },
  { id: 'm11', file: '河童蛙.png', tier: 'EX2', name: '河童蛙' },
  { id: 'm12', file: '土砂龙.png', tier: 'EX2', name: '土砂龙' },
  { id: 'm13', file: '水兽.png', tier: 'EX2', name: '水兽' },
  { id: 'm14', file: '伞鸟.png', tier: 'EX2', name: '伞鸟' },
  { id: 'm15', file: '岩龙.png', tier: 'EX2', name: '岩龙' },
  { id: 'm18', file: '将军镰蟹.png', tier: 'EX3', name: '将军镰蟹' },
  { id: 'm19', file: '绯天狗兽.png', tier: 'EX3', name: '绯天狗兽' },
  { id: 'm20', file: '雌火龙.png', tier: 'EX3', name: '雌火龙' },
  { id: 'm16', file: '人鱼龙.png', tier: 'EX3', name: '人鱼龙' },
  { id: 'm17', file: '泥鱼龙.png', tier: 'EX3', name: '泥鱼龙' },
  { id: 'm22', file: '飞雷龙.png', tier: 'EX3', name: '飞雷龙' },
  { id: 'm23', file: '蛮颚龙.png', tier: 'EX3', name: '蛮颚龙' },
  { id: 'm21', file: '毒妖鸟.png', tier: 'EX3', name: '毒妖鸟' },
  { id: 'm24', file: '怨虎龙.png', tier: 'EX4', name: '怨虎龙' },
  { id: 'm28', file: '泥翁龙.png', tier: 'EX4', name: '泥翁龙' },
  { id: 'm29', file: '妃蜘蛛.png', tier: 'EX4', name: '妃蜘蛛' },
  { id: 'm30', file: '雪鬼兽.png', tier: 'EX4', name: '雪鬼兽' },
  { id: 'm26', file: '冰牙龙.png', tier: 'EX4', name: '冰牙龙' },
  { id: 'm31', file: '冰人鱼龙.png', tier: 'EX4', name: '冰人鱼龙' },
  { id: 'm25', file: '刚缠兽.png', tier: 'EX4', name: '刚缠兽' },
  { id: 'm27', file: '迅龙.png', tier: 'EX4', name: '迅龙' },
  { id: 'm32', file: '熔翁龙.png', tier: 'EX5', name: '熔翁龙' },
  { id: 'm33', file: '火龙.png', tier: 'EX5', name: '火龙' },
  { id: 'm34', file: '电龙.png', tier: 'EX5', name: '电龙' },
  { id: 'm35', file: '泡狐龙.png', tier: 'EX5', name: '泡狐龙' },
  { id: 'm36', file: '雷狼龙.png', tier: 'EX5', name: '雷狼龙' },
  { id: 'm37', file: '冰狼龙.png', tier: 'EX5', name: '冰狼龙' },
  { id: 'm38', file: '千刃龙.png', tier: 'EX5', name: '千刃龙' },
  { id: 'm39', file: '轰龙.png', tier: 'EX5', name: '轰龙' },
  { id: 'm40', file: '角龙.png', tier: 'EX5', name: '角龙' },
  { id: 'm45', file: '炽妃蜘蛛.png', tier: 'EX6', name: '炽妃蜘蛛' },
  { id: 'm41', file: '棘龙.png', tier: 'EX6', name: '棘龙' },
  { id: 'm42', file: '黑蚀龙.png', tier: 'EX6', name: '黑蚀龙' },
  { id: 'm44', file: '金狮子.png', tier: 'EX6', name: '金狮子' },
  { id: 'm43', file: '爆鳞龙.png', tier: 'EX6', name: '爆鳞龙' },
  { id: 'm51', file: '嗟怨震天怨虎龙.png', tier: 'EX7', name: '嗟怨震天怨虎龙' },
  { id: 'm48', file: '棘茶龙.png', tier: 'EX7', name: '棘茶龙' },
  { id: 'm46', file: '金火龙.png', tier: 'EX7', name: '金火龙' },
  { id: 'm47', file: '银火龙.png', tier: 'EX7', name: '银火龙' },
  { id: 'm50', file: '激昂金狮子.png', tier: 'EX7', name: '激昂金狮子' },
  { id: 'm49', file: '红莲爆鳞龙.png', tier: 'EX7', name: '红莲爆鳞龙' },
  { id: 'm55', file: '混沌黑蚀龙.png', tier: 'EX8', name: '混沌黑蚀龙' },
  { id: 'm52', file: '怪异克服霞龙.png', tier: 'EX8', name: '怪异克服霞龙' },
  { id: 'm53', file: '怪异克服钢龙.png', tier: 'EX8', name: '怪异克服钢龙' },
  { id: 'm54', file: '怪异克服炎王龙.png', tier: 'EX8', name: '怪异克服炎王龙' },
  { id: 'm57', file: '怪异克服天彗龙.png', tier: 'EX9', name: '怪异克服天彗龙' },
  { id: 'm56', file: '怪异克服天廻龙.png', tier: 'EX9', name: '怪异克服天廻龙' },
  { id: 'm62', file: '原初形态爵银龙.png', tier: 'raging', name: '原初形态爵银龙' },
  { id: 'm58', file: '月迅龙.png', tier: 'raging', name: '月迅龙' },
  { id: 'm59', file: '焰狐龙.png', tier: 'raging', name: '焰狐龙' },
  { id: 'm61', file: '冰龙.png', tier: 'raging', name: '冰龙' },
  { id: 'm60', file: '岚龙.png', tier: 'raging', name: '岚龙' }
];
